  server:
    port: 9001
  spring:
    redis:
      host: 127.0.0.1
      port: 6379
    application:
      name: ihrm-company
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ihrm?useUnicode=true&characterEncoding=utf8
      username: root
      password: root
    jpa:
      database: MySQL
      show-sql: true
      open-in-view: true

  #注册到eureka的服务地址
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:6868/eureka/

    instance:
      prefer-ip-address: true
